import "server-only";
import {
  Document,
  Packer,
  Paragraph,
  TextRun,
  HeadingLevel,
} from "docx";

export interface PresenterSection {
  slide_number: number;
  title: string;
  script: string;
}

export async function buildPresenterDocx(
  deckTitle: string,
  sections: PresenterSection[]
): Promise<Buffer> {
  const children: Paragraph[] = [
    new Paragraph({
      heading: HeadingLevel.TITLE,
      children: [new TextRun({ text: deckTitle, bold: true })],
    }),
    new Paragraph({
      children: [
        new TextRun({
          text: "Presenter script — generated by SlideForge",
          italics: true,
        }),
      ],
    }),
    new Paragraph({ text: "" }),
  ];

  for (const section of sections) {
    children.push(
      new Paragraph({
        heading: HeadingLevel.HEADING_1,
        children: [
          new TextRun({
            text: `Slide ${section.slide_number}: ${section.title}`,
            bold: true,
          }),
        ],
      }),
      new Paragraph({
        children: [new TextRun({ text: section.script })],
        spacing: { after: 300 },
      })
    );
  }

  const doc = new Document({ sections: [{ children }] });
  return await Packer.toBuffer(doc);
}
